os: linux
dist: bionic
language: c

git:
  depth: 3


env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "RrpJQvAISnnRiobman1arWUZdsfIL29odr7hUVSAuMg0yHc6REH3HABIdI+4JOg7Q/xiG6gF5C133wCB4qGvgexwr9BubhfxtfT3J4CIbHUciAwnsrZ9OM8FjFwI0MWhBAxukWRE/+bfMwy2uQvY8UyXK3xUKuiLrDPUAaXBduQe6vrh/P4Pl/X+MVyinEPBqw7vxZzDfEYXDLaVhGVMMHBCZS0vPsi/EegmkK5CKVdNfqo1LO91XGCcFntD8thdzjoacqKl7G/q4nT0z1R9vHok5JpBCX+yW0HlfF9cLeIuVGJo6R36bhNpMAsNeR0AEAwOvF2SSzu7IaIrspP2DKymXTFS4HCswD7nGOgqTkhEXZXab7qXdliqo3kYPKXuIRPtbyskA/X3JJKbrsn6ULhPbFUID5teVAMjNt5UCwRVSXdN6ajQ6yYZ86TJNgEbJmnymwgBWqDqoww2CO94uJ7u3K+s0Ii3iJxJk28TtqrPHsdkw/WRqd9Zh+adyP4r37qtpdtiyjscyrZhpsa2BRbgWek6lvnPZ9YqXeMcy8HXV/SyP7XMZiDuROQf+HBbvPx50h+OD8wpe119+mIGv2sveKr7C5k3Co8j3bv+99RC+NaWG8h2oFRQ7phE5XPX0sF2bN/J9z6WoDk+heqkzwj9C1kKjeHq1BVCUAc+afU="


addons:
  apt:
    packages:
      - libpopt-dev
      - libselinux1-dev
      - libacl1-dev
      - automake
  coverity_scan:
    project:
      name: "cgzones/logrotate"
      description: "Build submitted via Travis CI"
    notification_email: cgzones@googlemail.com
    build_command_prepend: "./autogen.sh && ./configure --disable-silent-rules --with-selinux --with-acl --enable-werror && make clean"
    build_command: "make"
    branch_pattern: coverity_scan


script:
  - cat "${TRAVIS_BUILD_DIR}/cov-int/scm_log.txt"
